# Generated by Django 3.2.25 on 2026-04-15 07:57

import collections
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import multi_email_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_choice', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('lag', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_data_proj_id', models.CharField(max_length=100)),
                ('notification_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyWhenChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_choice', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=100)),
                ('proj_description', models.CharField(default='project description for template', max_length=400)),
                ('proj_start_date', models.DateTimeField(auto_now_add=True)),
                ('proj_end_date', models.DateTimeField(blank=True, null=True)),
                ('proj_deleted', models.BooleanField(default=False)),
                ('proj_archive', models.BooleanField(default=False)),
                ('proj_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('proj_section_master_name', models.CharField(blank=True, max_length=100, null=True)),
                ('proj_dropdown_field', models.CharField(blank=True, max_length=100, null=True)),
                ('proj_lock', models.BooleanField(default=False)),
                ('proj_doc_group', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectField',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_title', models.CharField(max_length=100, unique=True)),
                ('field_description', models.CharField(blank=True, max_length=200)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('bool', 'Boolean'), ('single-select', 'Single-Select'), ('multi-select', 'Multi-Select'), ('textarea', 'TextArea'), ('people', 'People'), ('signature', 'Signature')], max_length=20)),
                ('field_choice', models.ManyToManyField(blank=True, to='project_management.FieldChoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('proj_temp_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('proj_temp_status', models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('de', 'Deleted'), ('pe', 'Pending')], default='pe', max_length=2)),
                ('proj_temp_title', models.CharField(default='project title for template', max_length=100)),
                ('proj_temp_description', models.CharField(default='project description for template', max_length=400)),
                ('proj_temp_created_at', models.DateTimeField(auto_now_add=True)),
                ('proj_temp_edited_on', models.DateTimeField(auto_now=True)),
                ('proj_temp_doc_group', models.ManyToManyField(blank=True, to='auth.Group')),
                ('proj_temp_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_template_edited_by', to=settings.AUTH_USER_MODEL)),
                ('proj_temp_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionMasterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_choice', models.CharField(max_length=1000, unique=True)),
                ('special_char_choice', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_priority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLogHistory',
            fields=[
                ('task_log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Task Log ID')),
                ('project_id', models.CharField(blank=True, max_length=64, null=True)),
                ('task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('task_log_created_at', models.DateTimeField(auto_now_add=True)),
                ('task_log_message', models.TextField(blank=True, null=True)),
                ('task_log_status', models.CharField(choices=[('TASK_ADD', 'Task Added'), ('TASK_UPD', 'Task Updated'), ('TASK_DEL', 'Task Deleted'), ('TASK_COMP', 'Task Completed'), ('TASK_DUPL', 'Task Duplicated'), ('ATCH_ADD', 'Attachment Added'), ('ATCH_DEL', 'Attachment Deleted'), ('TASK_STAT_CHNG', 'Task Status Changed'), ('SIGNATURE_ADD', 'Signature Added'), ('SIGNATURE_UPD', 'Signature Updated'), ('SIGNATURE_DEL', 'Signature Deleted')], max_length=20)),
                ('task_log_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('parent', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('task_extra_column', jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('task_deleted', models.BooleanField(default=False)),
                ('is_section', models.BooleanField(default=False)),
                ('section_metadata', jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('section_label', jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_created_by', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.taskpriority')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.taskstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTemplateMetadata',
            fields=[
                ('section_temp_meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_task_id', models.CharField(max_length=100)),
                ('section_temp_meta_position', models.PositiveIntegerField(blank=True, null=True)),
                ('section_temp_meta_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('section_temp_meta_config', jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('section_task_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.projectfield')),
            ],
        ),
        migrations.CreateModel(
            name='SectionMetadataValues',
            fields=[
                ('section_meta_val_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_metadata_value', models.CharField(blank=True, max_length=10000, null=True)),
                ('section_task_id', models.CharField(max_length=100)),
                ('section_meta_val_position', models.PositiveIntegerField(blank=True, null=True)),
                ('section_task_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.projectfield')),
            ],
        ),
        migrations.CreateModel(
            name='SectionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_master_name', models.CharField(max_length=255)),
                ('section_master_metadata_name', models.CharField(max_length=255)),
                ('section_sub_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sub_choice', models.BooleanField(default=False)),
                ('section_sub_metadata_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('section_master_choice', models.ManyToManyField(blank=True, to='project_management.SectionMasterChoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplateField',
            fields=[
                ('proj_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_temp_field_position', models.CharField(blank=True, max_length=20, null=True)),
                ('proj_temp_field_hide', models.BooleanField(default=False)),
                ('proj_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.projecttemplate', verbose_name='Project Template ID')),
                ('proj_temp_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.projectfield')),
                ('proj_temp_field_editable', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_proj_id', models.CharField(max_length=100)),
                ('notify', models.BooleanField(default=False)),
                ('notify_other', multi_email_field.fields.MultiEmailField(blank=True, default=[], null=True)),
                ('notify_groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('notify_when_choice', models.ManyToManyField(blank=True, to='project_management.NotifyWhenChoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLogHistory',
            fields=[
                ('project_log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project Log ID')),
                ('project_id', models.CharField(blank=True, max_length=64, null=True)),
                ('project_log_created_at', models.DateTimeField(auto_now_add=True)),
                ('project_log_message', models.TextField(blank=True, null=True)),
                ('project_log_status', models.CharField(choices=[('PROJECT_ADD', 'Project Added'), ('PROJECT_UPD', 'Project Updated'), ('PROJECT_DEL', 'Project Deleted'), ('PROJECT_COPY', 'Project Copied'), ('PROJECT_DATE_CHNG', 'Project Date Changed'), ('PROJECT_ARCH', 'Project Archived'), ('PROJECT_REST', 'Project Restored'), ('PROJECT_STAT_CHNG', 'Project Status Changed'), ('PROJECT_SIGNATURE_ADD', 'Project Signature Added'), ('PROJECT_SIGNATURE_UPD', 'Project Signature Updated'), ('PROJECT_SIGNATURE_DEL', 'Project Signature Deleted')], max_length=30)),
                ('project_log_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectfield',
            name='field_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.projecttemplate'),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.projecttemplate'),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.projectstatus'),
        ),
        migrations.CreateModel(
            name='MetadataTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_field', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section_metadata_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_history', to='project_management.sectionmetadatavalues')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='project_management.task')),
            ],
        ),
    ]
