server {
    listen 80;
    server_name pms.3.88.69.141.nip.io;

    location / {
        return 301 https://$host$request_uri;
    }
}


server {

    listen 443 ssl;
    server_name pms.3.88.69.141.nip.io;

    ssl_certificate /etc/letsencrypt/live/pms.3.88.69.141.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pms.3.88.69.141.nip.io/privkey.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}