
from . import views
from django.conf.urls import url


urlpatterns = [


    # gantt chart urls
    url(r'^gantt-chart-view/(?P<proj_id>.*)/$', views.GanttChartView.as_view(), name='gantt-chart-view'),
    url(r'^data/task/(?P<pk>[0-9]+)$', views.task_update),
    url(r'^data/task', views.task_add),
    url(r'^data/link/(?P<pk>[0-9]+)$', views.link_update),
    url(r'^data/link', views.link_add),
    url(r'^data/(.*)$', views.data_list),

    # tree grid urls
    url(r'^tree-grid-view/(?P<proj_id>.*)/$', views.TreeGridView.as_view(), name='tree-grid-view'),
    url(r'^check-field-duplication/$', views.CheckFieldDuplication.as_view(), name='check-field-duplication'),
    url(r'^create-project-template/$', views.CreateProjectTemplate.as_view(), name='create-project-template'),
    url(r'^hide-column/$', views.HideColumn.as_view(), name='hide-column'),
    url(r'^show-column/$', views.ShowColumn.as_view(), name='show-column'),
    url(r'^create-new-project/$', views.CreateNewProject.as_view(), name='create-new-project'),
    url(r'^blank-project/$', views.BlankProject.as_view(), name='blank-project'),
    url(r'^use-template/$', views.UseTemplate.as_view(), name='use-template'),
    url(r'^add-new-task/$', views.AddNewTask.as_view(), name='add-new-task'),
    url(r'^add-new-subtask/$', views.AddNewSubtask.as_view(), name='add-new-subtask'),
    url(r'^remove-task/$', views.RemoveTask.as_view(), name='remove-task'),
    url(r'^duplicate-task/$', views.DuplicateTask.as_view(), name='duplicate-task'),
    url(r'^remove-all-task/$', views.RemoveAllTask.as_view(), name='remove-all-task'),
    url(r'^project-card-view/$', views.ProjectCardView.as_view(), name='project-card-view'),
    url(r'^get-update-project-view/$', views.GetUpdateProjectView.as_view(), name='get-update-project-view'),
    url(r'^post-update-project-view/$', views.PostUpdateProjectView.as_view(), name='post-update-project-view'),
    url(r'^project-data/$', views.project_data, name='project-data'),
    url(r'^delete-project-card-view/$', views.DeleteProjectCardView.as_view(), name='delete-project-card-view'),
    url(r'^edit-tree-grid-row/$', views.EditTreeGridRow.as_view(), name='edit-tree-grid-row'),
    url(r'^get-update-task-data/$', views.GetUpdateTaskData.as_view(), name='get-update-task-data'),
    url(r'^post-update-task-data/$', views.PostUpdateTaskData.as_view(), name='post-update-task-data'),
    url(r'^send-task-completed-email/$', views.SendTaskCompletedEmail.as_view(), name='send-task-completed-email'),
    url(r'^urgency-matrix-view/(?P<proj_id>.*)/$', views.UrgencyMatrixView.as_view(), name='urgency-matrix-view'),
    url(r'^urgency-matrix-ajax-view/$', views.UrgencyMatrixAjaxView.as_view(), name='urgency-matrix-ajax-view'),
    url(r'^projects-deleted/$', views.ProjectsDeleted.as_view(), name='projects-deleted'),
    url(r'^restore-deleted-project/$', views.RestoreDeletedProject.as_view(), name='restore-deleted-project'),
    url(r'^move-to-archive/$', views.MoveToArchive.as_view(), name='move-to-archive'),
    url(r'^projects-archive/$', views.ProjectsArchive.as_view(), name='projects-archive'),
    url(r'^restore-archive-project/$', views.RestoreArchiveProject.as_view(), name='restore-archive-project'),
    url(r'^permanently-delete-project/$', views.PermanentlyDeleteProject.as_view(), name='permanently-delete-project'),
    url(r'^my-tasks/$', views.MyTasks.as_view(), name='my-tasks'),
    url(r'^import-csv-file/$', views.ImportCSVFile.as_view(), name='import-csv-file'),
    url(r'^upload-csv-file/$', views.UploadCSVFile.as_view(), name='upload-csv-file'),
    url(r'^save-upload-csv-file/$', views.SaveUploadCSVFile.as_view(), name='save-upload-csv-file'),
    url(r'^create-project-field/$', views.CreateProjectField.as_view(), name='create-project-field'),
    url(r'^get-field-choice-values/$', views.GetFieldChoiceValues.as_view(), name='get-field-choice-values'),
    url(r'^post-field-choice-values/$', views.PostFieldChoiceValues.as_view(), name='post-field-choice-values'),
    url(r'^get-project-task-log-history/$', views.GetProjectTaskLogHistory.as_view(), name='get-project-task-log-history'),
    url(r'^export-to-excel/$', views.Export_to_Excel.as_view(), name='export-to-excel'),
    url(r'^reporting-dashboard/$', views.ReportingDashboard.as_view(), name='reporting-dashboard'),
    url(r'^more-charts/$', views.MoreCharts.as_view(), name='more-charts'),
    url(r'^get-editable-column-restriction/$', views.GetEditableColumnRestriction.as_view(), name='get-editable-column-restriction'),
    url(r'^get-editable-column-groups/$', views.GetEditableColumnGroups.as_view(), name='get-editable-column-groups'),
    url(r'^post-editable-column-groups/$', views.PostEditableColumnGroups.as_view(), name='post-editable-column-groups'),
    url(r'^deleted-tasks/$', views.DeletedTasks.as_view(), name='deleted-tasks'),
    url(r'^restore-deleted-task/$', views.RestoreDeletedTask.as_view(), name='restore-deleted-task'),
    url(r'^delete-task-permanently/$', views.DeleteTaskPermanently.as_view(), name='delete-task-permanently'),
    url(r'^add-new-section/$', views.AddNewSection.as_view(), name='add-new-section'),
    url(r'^get-section-label/$', views.GetSectionLabel.as_view(), name='get-section-label'),
    url(r'^add-section-label/$', views.AddSectionLabel.as_view(), name='add-section-label'),
    url(r'^update-section-label/$', views.UpdateSectionLabel.as_view(), name='update-section-label'),
    url(r'^delete-section-label/$', views.DeleteSectionLabel.as_view(), name='delete-section-label'),
    url(r'^add-update-delete-signature/$', views.AddUpdateDeleteSignature.as_view(), name='add-update-delete-signature'),
    url(r'^make-section-or-task/$', views.MakeSectionORTask.as_view(), name='make-section-or-task'),
    url(r'^get-section-metadata/$', views.GetSectionMetadata.as_view(), name='get-section-metadata'),
    url(r'^get-section-metadata-fields/$', views.GetSectionMetadataFields.as_view(), name='get-section-metadata-fields'),
    url(r'^add-section-metadata/$', views.AddSectionMetadata.as_view(), name='add-section-metadata'),
    url(r'^delete-section-metadata/$', views.DeleteSectionMetadata.as_view(), name='delete-section-metadata'),
    url(r'^update-section-metadata-order/$', views.UpdateSectionMetadataOrder.as_view(), name='update-section-metadata-order'),
    url(r'^nested-grid-metadata-view/$', views.NestedGridMetadataView.as_view(), name='nested-grid-metadata-view'),
    url(r'^update-column-order/$', views.UpdateColumnOrder.as_view(), name='update-column-order'),
    url(r'^update-row-order/$', views.UpdateRowOrder.as_view(), name='update-row-order'),
    url(r'^modify-nested-grid-row/$', views.ModifyNestedGridRow.as_view(), name='modify-nested-grid-row'),
    url(r'^get-metadata-field-choices/(?P<field_id>.*)/$', views.GetMetadataFieldChoices.as_view(), name='get-metadata-field-choices'),
    url(r'^update-section-metadata-values/$', views.UpdateSectionMetadataValues.as_view(), name='update-section-metadata-values'),
    url(r'^grid-add-update-delete-signature/$', views.GridAddUpdateDeleteSignature.as_view(), name='grid-add-update-delete-signature'),
    url(r'^get-section-header/$', views.GetSectionHeader.as_view(), name='get-section-header'),
    url(r'^save-section-header/$', views.SaveSectionHeader.as_view(), name='save-section-header'),
    url(r'^delete-section-header-group/$', views.DeleteSectionHeaderGroup.as_view(), name='delete-section-header-group'),
    url(r'^add-update-section-metadata-width/$', views.AddUpdateSectionMetadataWidth.as_view(), name='add-update-section-metadata-width'),
    url(r'^copy-project/$', views.CopyProject.as_view(), name='copy-project'),
    url(r'^copy-library-project/$', views.CopyLibraryProject.as_view(), name='copy-library-project'),
    url(r'^get-project-details-view/$', views.GetProjectDetailsView.as_view(), name='get-project-details-view'),
    url(r'^get-section-metadata-name/$', views.GetSectionMetadataName.as_view(), name='get-section-metadata-name'),
    url(r'^get-section-metadata-values/$', views.GetSectionMetadataValues.as_view(), name='get-section-metadata-values'),
    url(r'^fetch-metadata-tracking-values/$', views.FetchMetadataTrackingValues.as_view(), name='fetch-metadata-tracking-values'),
    url(r'^add-update-proj-signature/$', views.AddUpdateProjectSignature.as_view(), name='add-update-proj-signature'),
    url(r'^delete-proj-signature/$', views.DeleteProjectSignature.as_view(), name='delete-proj-signature'),
    url(r'^manage-section-master/$', views.ManageSectionMaster.as_view(), name='manage-section-master'),
    url(r'^create-section-master/$', views.CreateSectionMaster.as_view(), name='create-section-master'),
    url(r'^section-master-list/$', views.SectionMasterListView.as_view(), name='section-master-list'),
    url(r'^toggle-section-status/$', views.ToggleSectionMasterStatusView.as_view(), name='toggle-section-status'),
    url(r'^add-choice/$', views.AddChoice.as_view(), name='add-choice'),
    url(r'^remove-choice/$', views.RemoveChoice.as_view(), name='remove-choice'),
    url(r'^delete-section-master/$', views.DeleteSectionMaster.as_view(), name='delete-section-master'),
    url(r'^get-matching-choices/$', views.get_matching_choices, name='get-matching-choices'),
    url(r'^get-existing-choices/$', views.get_existing_choices, name='get-existing-choices'),
    url(r'^get-section-sub-metadata-choices/$', views.get_section_sub_metadata_choices, name='get-section-sub-metadata-choices'),
    url(r'^get-nested-combobox-choices/$', views.get_nested_combobox_choices, name='get-nested-combobox-choices'),
    url(r'^get-special-char-choice/$', views.get_special_char_choice, name="get-special-char-choice"),
    url(r'^get-project-log-history/$', views.GetProjectLogHistory.as_view(), name='get-project-log-history'),
    url(r'^export-excel-to-single-sheet/$', views.export_excel_to_single_sheet, name='export-excel-to-single-sheet'),
    url(r'^export-excel-to-grouped-hierarchy/$', views.export_excel_to_grouped_hierarchy, name='export-excel-to-grouped-hierarchy'),
    url(r'^export-excel-to-separate-sheets/$', views.export_excel_to_separate_sheets, name='export-excel-to-separate-sheets'),
    url(r'^export-to-pdf-file/$', views.export_to_pdf_file, name='export-to-pdf-file'),
    url(r'^update-special-char/(?P<pk>.*)/$', views.UpdateSpecialChar.as_view(), name='update-special-char'),
    url(r'^delete-special-char/(?P<pk>.*)/$', views.DeleteSpecialChar.as_view(), name='delete-special-char'),
    url(r'^project-lock-unlock/$', views.project_lock_unlock, name='project-lock-unlock'),
]
